[package]
name = "riot_local_auth"
version = "0.1.0"
authors = ["FX"]
license = "MIT"
edition = "2021"

[dependencies]
base64 = "0.21.7"
sysinfo = { version = "0.30.5", default-features = false }
thiserror = "1.0.56"
